steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/${PROJECT_ID}/opentelemetry-collector:latest'
      - '--tag=gcr.io/${PROJECT_ID}/opentelemetry-collector:${_RC_NAME}'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/opentelemetry-collector:latest'
  - 'gcr.io/$PROJECT_ID/opentelemetry-collector:${_RC_NAME}'
