receivers:
  dockerstats:
  nginxstats:
    stats_url: @NGINX_STATS_URL@
  vmage:
    build_date: @BUILD_DATE@
    vm_image_name: @IMAGE_NAME@
    vm_ready_time: @VM_READY_TIME@
    vm_start_time: @VM_START_TIME@

processors:
  resource:
    type: gae_instance
    labels: {
      "cloud.region": "@REGION@",
      "appengine.service.id": "@SERVICE@",
      "appengine.version.id": "@VERSION@",
      "appengine.instance.id": "@INSTANCE@",
  }

exporters:
  stackdriver:
    metric:
      prefix: custom.googleapis.com/flex/internal
  stackdriver/instance:
    metric:
      prefix: appengine.googleapis.com/flex/instance

service:
  pipelines:
    metrics:
      receivers: [vmage, nginxstats]
      processors: [resource]
      exporters: [stackdriver]
    metrics/instance:
      receivers: [dockerstats]
      processors: [resource]
      exporters: [stackdriver/instance]
