receivers:
  dockerstats:
  nginxstats:
    stats_url: @NGINX_STATS_URL@
  vmimageage:
    build_date: @BUILD_DATE@
    vm_image_name: @IMAGE_NAME@

processors:
  resource:
    type: gae_instance
    labels: {
      "cloud.region": "@REGION@",
      "appengine.service.id": "@SERVICE@",
      "appengine.version.id": "@VERSION@",
      "appengine.instance.id": "@INSTANCE@",
  }

exporters:
  stackdriver:
    metric_prefix: appengine.googleapis.com/flex/internal
  stackdriver/instance:
    metric_prefix: appengine.googleapis.com/flex/instance

service:
  pipelines:
    metrics:
            receivers: [vmimageage, nginxstats]
      processors: [resource]
      exporters: [stackdriver]
    metrics/instance:
      receivers: [dockerstats]
      processors: [resource]
      exporters: [stackdriver/instance]
