receivers:
  vmimageage:
    build_date: @BUILD_DATE@
    vm_image_name: @IMAGE_NAME@

processors:
  resource:
    type: gae_instance
    labels: {
      "cloud.region": "@REGION@",
      "appengine.service.id": "@SERVICE@",
      "appengine.version.id": "@VERSION@",
      "appengine.instance.id": "@INSTANCE@",
  }

exporters:
  stackdriver:
    metric_prefix: appengine.googleapis.com/flex/internal

service:
  pipelines:
    metrics:
      receivers: [vmimageage]
      processors: [resource]
      exporters: [stackdriver]
