receivers:
  vmimageage:
    build_date: @BUILD_DATE@
    vm_image_name: @IMAGE_NAME@

exporters:
  stackdriver/test_exporter:
    project: imccarten-flex-test
    metric_prefix: flex/opentelemetry

service:
  pipelines:
    metrics:
      receivers: [vmimageage]
      processors: []
      exporters: [stackdriver/test_exporter]
