# Config for building with Google Container Builder
#
# This produces a container with two tags, "latest" and _RC_NAME, which must be
# specified via a command-line flag.
#
# Run with:
#   gcloud container builds submit --config cloudbuild.yaml . \
#     --substitutions=_RC_NAME=20180101-RC00

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/api-verifier:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/api-verifier:${_RC_NAME}', '.']
images:
  - 'gcr.io/$PROJECT_ID/api-verifier:latest'
  - 'gcr.io/$PROJECT_ID/api-verifier:${_RC_NAME}'
