# Config for building with Google Cloud Build
#
# This produces a container with two tags, "latest" and _RC_NAME, which must be
# specified via a command-line flag.
#
# Run with:
#   gcloud builds submit --config cloudbuild.yaml . \
#     --substitutions=_RC_NAME=20180101-RC00

steps:
  - id: 'iap-watcher'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/iap-watcher:latest'
      - '--tag=gcr.io/$PROJECT_ID/iap-watcher:${_RC_NAME}'
      - '--target=iap-watcher'
      - '.'
  - id: 'iap-watcher-tester'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--target=iap-watcher-tester'
      - '--tag=gcr.io/$PROJECT_ID/iap-watcher-tester:latest'
      - '.'
  - id: 'iap-watcher-tests'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - 'gcr.io/$PROJECT_ID/iap-watcher-tester:latest'
    wait_for: ['iap-watcher-tester']
images:
  - 'gcr.io/$PROJECT_ID/iap-watcher:latest'
  - 'gcr.io/$PROJECT_ID/iap-watcher:${_RC_NAME}'
