name: Flex Otel Collector Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        working-directory: opentelemetry_collector
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Vet
      working-directory: opentelemetry_collector
      run: go vet -v ./...
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Test
      working-directory: opentelemetry_collector
      run: go test -v ./...
